### ISSUE TITLE
kernel does not start (python 3.9)

### ISSUE THREAD

**Issue by videlec** [videlec/pari-jupyter#1]
At commit 22a35e7 with pari 2.13 and python 3.9 kernel does not start. Here is what appears in the notebook console log
```
Kernel started: 0f896d80-54a7-45c2-88ef-5b94d189fa00, name: pari_jupyter
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincent/programming/pari-jupyter/PARIKernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=PARIKernel)
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 647, in initialize
    self.init_kernel()
  File "/usr/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 499, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "/usr/lib/python3.9/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "PARIKernel/kernel.pyx", line 105, in PARIKernel.kernel.PARIKernel.__init__
    self.io = PARIKernelIO(self)
  File "PARIKernel/io.pyx", line 67, in PARIKernel.io.PARIKernelIO.__init__
    self.stdout_stream = OutStream(kernel.session,
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 351, in __init__
    warnings.warn(
TypeError: argument for warn() given by name ('stacklevel') and position (3)
```

**Comment by videlec** [comment]
Fixed in 926289f
